services:
  db:
    image: mysql:8
    container_name: restaurant_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_management
    ports:
      - "3307:3306"
    volumes:
      - restaurant_management_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: restaurant_management_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurant_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  restaurant_management_data:
